In [ ]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

In [ ]:
data = pd.read_csv('статистика_старт.csv')
data.shape
data = data.rename(columns={'Unnamed: 0': 'region'}).set_index('region')

In [ ]:
regM=['Ханты-Мансийский автономный округ - Югра (Тюменская область)', 'Ямало-Ненецкий автономный округ (Тюменская область)', 'Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа)',
      'Республика Алтай', 'Республика Бурятия', 'Республика Тыва', 'Республика Хакасия',
      'Алтайский край', 'Забайкальский край', 'Красноярский край',
      'Иркутская область', 'Новосибирская область', 'Омская область', 'Томская область',
      'Агинский Бурятский округ (Забайкальский край)']
regM_=['Ханты-Мансийск', 'Тюмень',
       'Горно-Алтайск', 'Улан-Удэ', 'Северобайкальск', 'Кызыл', 'Абакан', 'Барнаул', 'Красноярск', 'Иркутск',
       'Кемерово', 'Юрга', 'Новосибирск', 'Омск', 'Томск']
reg=regM[0]
reg_zap=''

In [ ]:
def f(x):
    return x[12:]

#data.rename(index={'Омская область': 'Омск', 'Томская область': 'Томск'})

In [ ]:
#A1 - Доходы гостиниц и аналогичных средств размещения
A1=data[1:15]

In [ ]:
#A2 - Число гостиниц и средств размещения
A2=data[18:32]
A2
#A2.info()

,2002,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
region,,,,,,,,,,,,,,,,,
Ханты-Мансийский автономный округ - Югра (Тюменская область),NaN,NaN,NaN,NaN,NaN,NaN,NaN,136,138,164,180,182,201,236,245,250,210
Ямало-Ненецкий автономный округ (Тюменская область),NaN,NaN,NaN,NaN,NaN,NaN,NaN,67,59,72,63,64,81,87,93,100,103
Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа),NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,74,101,107,138,148,162,169,198
Республика Алтай,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113,127,131,131,105,120,100,101,103,110
Республика Бурятия,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124,175,193,233,203,241,256,280,254,244
Республика Тыва,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,17,19,17,20,17,14,17,16
Республика Хакасия,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,34,36,21,41,50,39,49,54,47
Алтайский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,155,167,202,200,188,233,232,316,315,318
Забайкальский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,96,105,105,114,115,117,120,123,131
Красноярский край,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198,182,216,240,211,219,265,280,301,288
Иркутская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175,193,202,215,240,223,211,252,272,282
Новосибирская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,97,117,148,150,150,166,206,205,201
Омская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70,72,75,83,85,150,173,113,139,125
Томская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61,60,59,61,58,67,141,144,168,157

In [ ]:
#A3 - Численность размещенных лиц в гостиницах и ананлогичных средствах размещения
A3=data[34:48]
#A3
#A3.info()

In [ ]:
#A4 - Число ночевок в гостиницах и ананлогичных средствах размещения
A4=data[51:65]
#A4
#A4.info()

In [ ]:
#A5 - Средняя численность работников, включая внешних совместителей
A5=data[67:85]
A5.index=A5.index.map(f)
A5=A5.drop(labels=['Таймырский (Долгано-Ненецкий) автономный округ (Красноярский край)', 'Эвенкийский автономный округ (Красноярский край)','Усть-Ордынский Бурятский округ'], axis=0)
#A5
#A5.info()

In [ ]:
#A6 - Число туристских фирм
A6=data[87:105]
A6.index=A6.index.map(f)
A6=A6.drop(labels=['Таймырский (Долгано-Ненецкий) автономный округ (Красноярский край)', 'Эвенкийский автономный округ (Красноярский край)','Усть-Ордынский Бурятский округ'], axis=0)
A6
#A6.info()

,2002,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
region,,,,,,,,,,,,,,,,,
Ханты-Мансийский автономный округ - Югра (Тюменская область),40,37,43,48,62,67,51,88,96,114,148,161,118,121,149,158,153
Ямало-Ненецкий автономный округ (Тюменская область),3,7,6,7,10,16,7,8,8,18,25,27,26,20,22,15,29
Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа),,,,,,,,,,,174,218,218,149,216,225,237
Республика Алтай,4,23,12,10,7,14,18,61,57,57,60,61,79,73,29,22,24
Республика Бурятия,8,21,23,23,28,41,41,58,48,57,42,42,51,54,43,53,54
Республика Тыва,3,6,8,7,5,6,12,15,11,7,9,9,9,12,14,11,7
Республика Хакасия,7,8,13,9,17,22,16,26,27,25,31,43,43,37,49,51,41
Алтайский край,44,56,76,77,87,100,95,110,121,144,147,161,167,133,155,160,164
Забайкальский край,15,20,31,35,38,37,41,50,62,59,65,61,26,57,45,41,33
Агинский Бурятский округ (Забайкальский край),0,,2,2,2,,,,,,,,,,,,
Красноярский край,37,51,59,75,77,97,111,145,170,283,314,335,330,343,351,363,333
Иркутская область,50,65,90,112,130,95,126,145,207,158,202,182,135,197,248,251,227
Новосибирская область,50,72,84,108,117,117,165,236,273,277,283,286,268,222,327,342,286
Омская область,58,83,98,106,115,115,120,143,166,191,209,226,206,186,220,207,220
Томская область,45,54,62,66,70,76,83,95,128,131,139,149,116,116,133,146,108

In [ ]:
#A7 - Средства, поступившие от реализации туристкого продукта
A7=data[108:122]
A7.index=A7.index.map(f)
#A7
#A7.info()

In [ ]:
#A8 - Число реализованных турпакетов населению
A8=data[124:138]
A8.index=A8.index.map(f)
#A8
#A8.info()

In [ ]:
#A9 - Индекс стоимости жизни
A9=data[143:158]
A9.index=A9.index.map(f)
A9
#A9.info()

,2002,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
region,,,,,,,,,,,,,,,,,
Тюмень,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.9,105.76,105.03,103.86,100.71,100.36,102.58,102.66,102.4,100.71
Ханты-Мансийск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132.69,130.95,128.24,126.12,124.25,121.62,120.52,119.83,118.08,117.86
Горно-Алтайск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.92,103.3,104.69,104.09,109.72,110.16,109.29,108.18,104.81,104.02
Улан-Удэ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.2,98.36,99.51,97.93,98.06,98.58,97.18,96.47,97.23,97.9
Северобайкальск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.89,118.81,121.29,118.92,117.33,114.3,109.44,106.26,109.32,110.6
Кызыл,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.49,100.39,100.46,99.39,97.73,97.88,96.9,94.89,95.29,94.69
Абакан,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.28,99.12,98.06,100.55,99.71,95.63,94.94,92.67,93.56,94.8
Барнаул,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.05,88.94,87.83,88.29,88.29,88.55,90.05,89.73,90.13,91.3
Красноярск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.35,101.78,102.92,103.95,100.29,100.13,101.49,100.23,99.3,99.93
Иркутск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.29,100.97,101.43,101.66,98.31,98.96,100.18,98.44,97.73,98.21
Кемерово,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.79,86.87,87.41,89.75,89.39,89.07,87.68,86.09,85.62,87.91
Юрга,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.5,84.74,85.85,87.46,84.76,83.55,82.82,82.55,84.4,86.41
Новосибирск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.09,102.43,102.27,103.11,102.01,102.33,102,101.27,99.31,98.49
Омск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.52,83.09,83.14,84.12,85.15,85.31,85.26,84.67,85.19,87.66
Томск,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.77,97.85,97.69,98.08,97.27,97.02,97.17,96.47,96.8,98.13

In [ ]:
ItogI = pd.DataFrame()
ItogP = pd.DataFrame()
for reg in regM:
  print(reg)
  Itog = pd.DataFrame()
  a = A1.loc[(A1.index == reg)]
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
  Itog = Itog.append(a)
  a = A2.loc[(A2.index == reg)]
  a['крит'] = 'Число гостиниц и средств размещения'
  Itog = Itog.append(a)
  a = A3.loc[(A3.index == reg)]
  a['крит'] = 'Численность размещенных лиц в гостиницах и ананлогичных средствах размещения'
  Itog = Itog.append(a)
  a = A4.loc[(A4.index == reg)]
  a['крит'] = 'Число ночевок в гостиницах и ананлогичных средствах размещения'
  Itog = Itog.append(a)
  a = A5.loc[(A5.index == reg)]
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
  Itog = Itog.append(a)
  a = A6.loc[(A6.index == reg)]
  a['крит'] = 'Число туристских фирм'
  Itog = Itog.append(a)
  a = A7.loc[(A7.index == reg)]
  a['крит'] = 'Средства, поступившие от реализации туристкого продукта'
  Itog = Itog.append(a)
  a = A8.loc[(A8.index == reg)]
  a['крит'] = 'Число реализованных турпакетов населению'
  Itog = Itog.append(a)
  #a = A9.loc[(A9.index == reg)|(A9.index == reg_zap)]
  #a['крит'] = 'Индекс стоимости жизни'
  #Itog = Itog.append(a)

  Itog=Itog.set_index('крит')
  Itog=Itog.T
  #print(1)

  #a1=[]
  #for i in range(18):
  #  a1.append(reg)
  #def r(x)
  Itog['регион']=reg
  #display(Itog)

  ItogI=pd.concat([ItogI, Itog[7:]], axis=0).reset_index(drop=True)

ItogI
#pd.DataFrame(a1)

Ханты-Мансийский автономный округ - Югра (Тюменская область)
Ямало-Ненецкий автономный округ (Тюменская область)
Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа)
Республика Алтай
Республика Бурятия
Республика Тыва
Республика Хакасия
Алтайский край
Забайкальский край
Красноярский край
Иркутская область
Новосибирская область
Омская область
Томская область

<ipython-input-374-8bd632c3c0d3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число гостиниц и средств размещения'
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Численность размещенных лиц в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число ночевок в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
<ipython-input-374-8bd632c3c0d3>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число туристских фирм'
<ipython-input-374-8bd632c3c0d3>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средства, поступившие от реализации туристкого продукта'
<ipython-input-374-8bd632c3c0d3>:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число реализованных турпакетов населению'
<ipython-input-374-8bd632c3c0d3>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число гостиниц и средств размещения'
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Численность размещенных лиц в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число ночевок в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
<ipython-input-374-8bd632c3c0d3>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число туристских фирм'
<ipython-input-374-8bd632c3c0d3>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средства, поступившие от реализации туристкого продукта'
<ipython-input-374-8bd632c3c0d3>:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число реализованных турпакетов населению'
<ipython-input-374-8bd632c3c0d3>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число гостиниц и средств размещения'
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Численность размещенных лиц в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число ночевок в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
<ipython-input-374-8bd632c3c0d3>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число туристских фирм'
<ipython-input-374-8bd632c3c0d3>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средства, поступившие от реализации туристкого продукта'
<ipython-input-374-8bd632c3c0d3>:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число реализованных турпакетов населению'
<ipython-input-374-8bd632c3c0d3>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число гостиниц и средств размещения'
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Численность размещенных лиц в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число ночевок в гостиницах и ананлогичных средствах размещения'
<ipython-input-374-8bd632c3c0d3>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
<ipython-input-374-8bd632c3c0d3>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число туристских фирм'
<ipython-input-374-8bd632c3c0d3>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средства, поступившие от реализации туристкого продукта'
<ipython-input-374-8bd632c3c0d3>:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число реализованных турпакетов населению'
<ipython-input-374-8bd632c3c0d3>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Доходы гостиниц и аналогичных средств размещения'
<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число гостиниц и средств размещения'
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

Агинский Бурятский округ (Забайкальский край)

<ipython-input-374-8bd632c3c0d3>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Средняя численность работников, включая внешних совместителей'
<ipython-input-374-8bd632c3c0d3>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['крит'] = 'Число туристских фирм'
<ipython-input-374-8bd632c3c0d3>:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)
<ipython-input-374-8bd632c3c0d3>:29: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Itog = Itog.append(a)

крит,Доходы гостиниц и аналогичных средств размещения,Число гостиниц и средств размещения,Численность размещенных лиц в гостиницах и ананлогичных средствах размещения,Число ночевок в гостиницах и ананлогичных средствах размещения,"Средняя численность работников, включая внешних совместителей",Число туристских фирм,"Средства, поступившие от реализации туристкого продукта",Число реализованных турпакетов населению,регион
0,2228536.39,136,362715,965877,345,88,NaN,20519,Ханты-Мансийский автономный округ - Югра (Тюме...
1,2040628.19,138,308806,886058.99,325,96,250289.59,26776.99,Ханты-Мансийский автономный округ - Югра (Тюме...
2,2465505.6,164,397251,1280459,436,114,262968.49,30207,Ханты-Мансийский автономный округ - Югра (Тюме...
3,2720895.1,180,456728.99,1376499,500,148,299289.9,36163,Ханты-Мансийский автономный округ - Югра (Тюме...
4,2954950.8,182,423365.99,1321813.99,553,161,359773.9,37618.99,Ханты-Мансийский автономный округ - Югра (Тюме...
...,...,...,...,...,...,...,...,...,...
145,NaN,NaN,NaN,NaN,,,NaN,NaN,Агинский Бурятский округ (Забайкальский край)
146,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,Агинский Бурятский округ (Забайкальский край)
147,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,Агинский Бурятский округ (Забайкальский край)
148,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,Агинский Бурятский округ (Забайкальский край)
149,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,Агинский Бурятский округ (Забайкальский край)

In [ ]:
ItogI.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   Доходы гостиниц и аналогичных средств размещения                              110 non-null    object
 1   Число гостиниц и средств размещения                                           110 non-null    object
 2   Численность размещенных лиц в гостиницах и ананлогичных средствах размещения  110 non-null    object
 3   Число ночевок в гостиницах и ананлогичных средствах размещения                110 non-null    object
 4   Средняя численность работников, включая внешних совместителей                 90 non-null     object
 5   Число туристских фирм                                                         150 non-null    object
 6   Средства, поступившие от реализации туристкого продукта                       126 non-null    object
 7   Число реализованных турпакетов населению                                      140 non-null    object
 8   регион                                                                        150 non-null    object
dtypes: object(9)
memory usage: 10.7+ KB

In [ ]:
for t in range(len(ItogI)-1, -1,-1):
  if ItogI.iloc[t].isnull().sum()>5:
    ItogI=ItogI.drop(labels=[t], axis=0)
ItogI = ItogI.reset_index(drop=True)
ItogI

крит,Доходы гостиниц и аналогичных средств размещения,Число гостиниц и средств размещения,Численность размещенных лиц в гостиницах и ананлогичных средствах размещения,Число ночевок в гостиницах и ананлогичных средствах размещения,"Средняя численность работников, включая внешних совместителей",Число туристских фирм,"Средства, поступившие от реализации туристкого продукта",Число реализованных турпакетов населению,регион
0,2228536.39,136,362715,965877,345,88,NaN,20519,Ханты-Мансийский автономный округ - Югра (Тюме...
1,2040628.19,138,308806,886058.99,325,96,250289.59,26776.99,Ханты-Мансийский автономный округ - Югра (Тюме...
2,2465505.6,164,397251,1280459,436,114,262968.49,30207,Ханты-Мансийский автономный округ - Югра (Тюме...
3,2720895.1,180,456728.99,1376499,500,148,299289.9,36163,Ханты-Мансийский автономный округ - Югра (Тюме...
4,2954950.8,182,423365.99,1321813.99,553,161,359773.9,37618.99,Ханты-Мансийский автономный округ - Югра (Тюме...
...,...,...,...,...,...,...,...,...,...
135,535920.4,67,70491.99,168025.99,418,116,309415.2,30996.99,Томская область
136,705352.8,141,189645.99,343986.99,NaN,116,371672.8,21147.99,Томская область
137,721877.7,144,192340,468973,NaN,133,498566.3,21184.99,Томская область
138,747416.6,168,207340,453660.99,NaN,146,673320.6,25874,Томская область
139,845138.1,157,191059.99,414232.99,NaN,108,461136.3,20966,Томская область

In [ ]:
ItogI.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 9 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   Доходы гостиниц и аналогичных средств размещения                              110 non-null    object
 1   Число гостиниц и средств размещения                                           110 non-null    object
 2   Численность размещенных лиц в гостиницах и ананлогичных средствах размещения  110 non-null    object
 3   Число ночевок в гостиницах и ананлогичных средствах размещения                110 non-null    object
 4   Средняя численность работников, включая внешних совместителей                 84 non-null     object
 5   Число туристских фирм                                                         140 non-null    object
 6   Средства, поступившие от реализации туристкого продукта                       126 non-null    object
 7   Число реализованных турпакетов населению                                      140 non-null    object
 8   регион                                                                        140 non-null    object
dtypes: object(9)
memory usage: 10.0+ KB

In [ ]:
ItogP=ItogI[:1]
for t in range(len(ItogI)-1, -1,-1):
  if pd.isna(ItogI['Средняя численность работников, включая внешних совместителей'].loc[ItogI.index[t]]):
    #ItogP=ItogP.appeng(ItogI.iloc[t])
    ItogP=pd.concat([ItogP, ItogI.iloc[t]], axis=0).reset_index(drop=True)
    #print(ItogI.iloc[t])
    #display(ItogI.iloc[t])
    ItogI=ItogI.drop(labels=[t], axis=0)
ItogI = ItogI.reset_index(drop=True)
#ItogP = ItogP.drop(['Средняя численность работников, включая внешних совместителей'], axis=1).reset_index(drop=True)
#ItogI
ItogP

крит,Доходы гостиниц и аналогичных средств размещения,Число гостиниц и средств размещения,Численность размещенных лиц в гостиницах и ананлогичных средствах размещения,Число ночевок в гостиницах и ананлогичных средствах размещения,"Средняя численность работников, включая внешних совместителей",Число туристских фирм,"Средства, поступившие от реализации туристкого продукта",Число реализованных турпакетов населению,регион
0,2228536.39,136,362715,965877,345,88,NaN,20519,Ханты-Мансийский автономный округ - Югра (Тюме...

In [ ]:
print(list(ItogI.iloc[13]))

['    ', '    ', '    ', '    ', '    ', '    ', '    ', '    ', 'Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа)']

In [ ]:
ItogII=pd.get_dummies (ItogI, columns=['регион'])
ItogPP=pd.get_dummies (ItogP, columns=['регион'])

In [ ]:
ItogII.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 22 columns):
 #   Column                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                           --------------  -----
 0   Доходы гостиниц и аналогичных средств размещения                                                                 66 non-null     object
 1   Число гостиниц и средств размещения                                                                              66 non-null     object
 2   Численность размещенных лиц в гостиницах и ананлогичных средствах размещения                                     66 non-null     object
 3   Число ночевок в гостиницах и ананлогичных средствах размещения                                                   66 non-null     object
 4   Средняя численность работников, включая внешних совместителей                                                    84 non-null     object
 5   Число туристских фирм                                                                                            84 non-null     object
 6   Средства, поступившие от реализации туристкого продукта                                                          70 non-null     object
 7   Число реализованных турпакетов населению                                                                         84 non-null     object
 8   регион_Алтайский край                                                                                            84 non-null     uint8
 9   регион_Забайкальский край                                                                                        84 non-null     uint8
 10  регион_Иркутская область                                                                                         84 non-null     uint8
 11  регион_Красноярский край                                                                                         84 non-null     uint8
 12  регион_Новосибирская область                                                                                     84 non-null     uint8
 13  регион_Омская область                                                                                            84 non-null     uint8
 14  регион_Республика Алтай                                                                                          84 non-null     uint8
 15  регион_Республика Бурятия                                                                                        84 non-null     uint8
 16  регион_Республика Тыва                                                                                           84 non-null     uint8
 17  регион_Республика Хакасия                                                                                        84 non-null     uint8
 18  регион_Томская область                                                                                           84 non-null     uint8
 19  регион_Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа)  84 non-null     uint8
 20  регион_Ханты-Мансийский автономный округ - Югра (Тюменская область)                                              84 non-null     uint8
 21  регион_Ямало-Ненецкий автономный округ (Тюменская область)                                                       84 non-null     uint8
dtypes: object(8), uint8(14)
memory usage: 6.5+ KB

In [ ]:
#for j in Itog.columns:
#  print(1)
#  Y2 = Itog[j].tolist()
#  for i in range(len(Y2)):
#   Y2[i]=Y2[i][1:]
#    Y2[i]=float(Y2[i])
from math import nan
def fl(x):
  if x=='    ':
    return(nan)
  else:
    return(float(x))
for j in ItogII.columns[:-2]:
  ItogII[j]=ItogII[j].map(fl)
for j in ItogPP.columns[:-2]:
  ItogPP[j]=ItogPP[j].map(fl)

In [ ]:
for i in ItogII.columns:
    ItogII[i]=ItogII[i].fillna(round(ItogII[i].mean(),0))
for i in ItogPP.columns:
    ItogPP[i]=ItogPP[i].fillna(round(ItogII[i].mean(),0))
ItogII

,Доходы гостиниц и аналогичных средств размещения,Число гостиниц и средств размещения,Численность размещенных лиц в гостиницах и ананлогичных средствах размещения,Число ночевок в гостиницах и ананлогичных средствах размещения,"Средняя численность работников, включая внешних совместителей",Число туристских фирм,"Средства, поступившие от реализации туристкого продукта",Число реализованных турпакетов населению,регион_Алтайский край,регион_Забайкальский край,...,регион_Новосибирская область,регион_Омская область,регион_Республика Алтай,регион_Республика Бурятия,регион_Республика Тыва,регион_Республика Хакасия,регион_Томская область,регион_Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа),регион_Ханты-Мансийский автономный округ - Югра (Тюменская область),регион_Ямало-Ненецкий автономный округ (Тюменская область)
0,2228536.39,136.0,362715.00,965877.00,345.0,88.0,773094.00,20519.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2040628.19,138.0,308806.00,886058.99,325.0,96.0,250289.59,26776.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2465505.60,164.0,397251.00,1280459.00,436.0,114.0,262968.49,30207.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,2720895.10,180.0,456728.99,1376499.00,500.0,148.0,299289.90,36163.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,2954950.80,182.0,423365.99,1321813.99,553.0,161.0,359773.90,37618.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,493720.70,60.0,115347.99,245460.00,483.0,128.0,269156.20,27697.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
80,501149.79,59.0,116991.99,244804.99,439.0,131.0,262660.59,25024.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
81,491025.70,61.0,115645.99,219681.00,500.0,139.0,274363.70,37935.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
82,417181.40,58.0,94822.99,198855.99,516.0,149.0,266895.59,41458.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
83,535920.40,67.0,70491.99,168025.99,418.0,116.0,309415.20,30996.99,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
y=ItogII["Средняя численность работников, включая внешних совместителей"]
X=ItogII.drop(["Средняя численность работников, включая внешних совместителей"], axis=1)

In [ ]:
y

0     345.0
1     325.0
2     436.0
3     500.0
4     553.0
      ...
79    483.0
80    439.0
81    500.0
82    516.0
83    418.0
Name: Средняя численность работников, включая внешних совместителей, Length: 84, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
X

In [ ]:
y

In [ ]:
X.corrwith(y)

Доходы гостиниц и аналогичных средств размещения                                                                   0.396405
Число гостиниц и средств размещения                                                                                0.385338
Численность размещенных лиц в гостиницах и ананлогичных средствах размещения                                       0.521995
Число ночевок в гостиницах и ананлогичных средствах размещения                                                     0.510578
Число туристских фирм                                                                                              0.931178
Средства, поступившие от реализации туристкого продукта                                                            0.725455
Число реализованных турпакетов населению                                                                           0.578416
регион_Алтайский край                                                                                              0.031725
регион_Забайкальский край                                                                                         -0.035823
регион_Иркутская область                                                                                           0.143876
регион_Красноярский край                                                                                           0.396573
регион_Новосибирская область                                                                                       0.632348
регион_Омская область                                                                                              0.112898
регион_Республика Алтай                                                                                           -0.175079
регион_Республика Бурятия                                                                                         -0.206200
регион_Республика Тыва                                                                                            -0.357790
регион_Республика Хакасия                                                                                         -0.311610
регион_Томская область                                                                                             0.006198
регион_Тюменская область (кроме Ханты-Мансийского автономного округа-Югры и Ямало-Ненецкого автономного округа)    0.103146
регион_Ханты-Мансийский автономный округ - Югра (Тюменская область)                                               -0.023633
регион_Ямало-Ненецкий автономный округ (Тюменская область)                                                        -0.316630
dtype: float64

In [ ]:
Itog.corr()

In [ ]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np

In [ ]:
lr = LinearRegression().fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [ ]:
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {mean_absolute_percentage_error(y_test, y_pred)}')
print(f'R^2: {lr.score(X_test, y_test)}')

MAE: 50.725491411125276
MSE: 6649.223277776814
RMSE: 81.54276962292128
MAPE: 0.16113174264879054
R^2: 0.9175121732429622

In [ ]:
#y_pred = lr.predict(ItogPP)